"""
LBKT Preprocessing Script for Merged Dataset

Preprocess merged_student_question_history.csv into LBKT-ready sequences.

Usage (from lbkt/ directory):
    python lbkt_preprocess_merged.py \
        --input ../merge_script/merged_student_question_history.csv \
        --output_dir lbkt_processed \
        --min_seq_len 3

This script:
  1. Reads the wide merged CSV where each row is one student.
  2. Dynamically detects question columns (q*_id).
  3. Extracts ordered question and correctness sequences.
  4. Calculates completion rates for fairness analysis.
  5. Maps raw question IDs to contiguous indices [0, num_questions - 1].
  6. Drops users with short sequences (length < min_seq_len).
  7. Uses unified splits from data/splits.json (generated by generate_splits.py).
  8. Saves the result as pickles plus a JSON metadata file.
"""

import argparse
import json
import math
import os
import pickle
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


def parse_args():
    parser = argparse.ArgumentParser(description="Preprocess merged CSV for LBKT")
    parser.add_argument(
        "--input",
        type=str,
        default="../merge_script/merged_student_question_history.csv",
        help="Path to merged wide CSV file",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="lbkt_processed",
        help="Directory to save processed outputs",
    )
    parser.add_argument(
        "--min_seq_len",
        type=int,
        default=3,
        help="Minimum sequence length per user",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for splitting (only used if splits.json not found)",
    )
    return parser.parse_args()


def find_question_indices(columns: List[str]) -> List[int]:
    """Return sorted list of N such that qN_id exists."""
    q_indices = []
    for col in columns:
        if col.startswith("q") and col.endswith("_id"):
            try:
                middle = col[1 : col.rindex("_")]
                idx = int(middle)
                q_indices.append(idx)
            except Exception:
                continue
    q_indices = sorted(set(q_indices))
    if not q_indices:
        raise ValueError("No qN_id columns found in input CSV.")
    return q_indices


def normalize_correct_value(val) -> int:
    """Normalize correctness value to 0 or 1."""
    if val is None or (isinstance(val, float) and math.isnan(val)):
        raise ValueError("Missing correctness")

    if isinstance(val, (int, float, np.integer, np.floating)):
        return 1 if float(val) > 0.0 else 0

    s = str(val).strip().lower()
    if s == "":
        raise ValueError("Empty correctness")

    truthy = {"1", "true", "t", "yes", "y", "correct"}
    falsey = {"0", "false", "f", "no", "n", "incorrect"}

    if s in truthy:
        return 1
    if s in falsey:
        return 0

    try:
        f = float(s)
        return 1 if f > 0.0 else 0
    except Exception:
        raise ValueError(f"Unrecognized correctness value: {val!r}")


def extract_sequence_for_row(
    row: pd.Series,
    q_indices: List[int],
    correctness_priority: List[str],
) -> Tuple[List[str], List[int]]:
    """Extract (question_ids, correctness) sequence for a single row."""
    question_ids = []
    correctness = []

    for idx in q_indices:
        qid_col = f"q{idx}_id"
        if qid_col not in row.index:
            continue

        qid_val = row[qid_col]
        if pd.isna(qid_val):
            continue

        qid = str(int(qid_val)) if isinstance(qid_val, float) else str(qid_val)

        correct_val = None
        for suffix in correctness_priority:
            col_name = f"q{idx}_{suffix}"
            if col_name in row.index:
                candidate = row[col_name]
                if not pd.isna(candidate):
                    try:
                        correct_val = normalize_correct_value(candidate)
                        break
                    except ValueError:
                        pass

        if correct_val is not None:
            question_ids.append(qid)
            correctness.append(correct_val)

    return question_ids, correctness


def main():
    args = parse_args()
    np.random.seed(args.seed)

    print(f"Loading data from: {args.input}")
    df = pd.read_csv(args.input, low_memory=False)
    print(f"Loaded {len(df)} rows, {len(df.columns)} columns")

    # Find question indices
    q_indices = find_question_indices(list(df.columns))
    total_q_slots = len(q_indices)
    print(f"Detected {total_q_slots} question slots: q{q_indices[0]}_id ... q{q_indices[-1]}_id")

    # Correctness column priority
    correctness_priority = ["correct", "answerchoiceselected_iscorrect", "correctresponse"]

    # Extract sequences
    user_sequences: Dict[str, Tuple[List[str], List[int]]] = {}
    completion_rates: Dict[str, float] = {}

    print("Extracting sequences...")
    for idx, row in df.iterrows():
        user_id = str(row.get("UserId", idx))
        q_list, c_list = extract_sequence_for_row(row, q_indices, correctness_priority)

        if len(q_list) >= args.min_seq_len:
            user_sequences[user_id] = (q_list, c_list)
            completion_rates[user_id] = len(q_list) / total_q_slots

    print(f"Users with >= {args.min_seq_len} interactions: {len(user_sequences)}")

    # Build question ID mapping
    all_qids = set()
    for q_list, _ in user_sequences.values():
        all_qids.update(q_list)

    sorted_qids = sorted(all_qids, key=lambda x: int(x) if x.isdigit() else x)
    qid_to_idx = {qid: i for i, qid in enumerate(sorted_qids)}
    num_questions = len(sorted_qids)
    print(f"Unique questions: {num_questions}")

    # Convert to integer sequences
    processed_sequences = {}
    for user_id, (q_list, c_list) in user_sequences.items():
        q_idx = np.array([qid_to_idx[q] for q in q_list], dtype=np.int64)
        c_arr = np.array(c_list, dtype=np.int64)
        processed_sequences[user_id] = (q_idx, c_arr)

    # User-level train/valid/test split using unified splits.json
    # Check for unified splits first (same as DKT/GKT/reKT)
    base_dir = os.path.dirname(os.path.abspath(__file__))
    splits_path = os.path.join(base_dir, "..", "data", "splits.json")
    
    if os.path.exists(splits_path):
        print(f"Loading unified splits from {splits_path} ...")
        with open(splits_path, "r") as f:
            splits = json.load(f)
        
        # Create sets for O(1) lookup
        train_set = set(splits["train"])
        valid_set = set(splits["valid"])
        test_set = set(splits["test"])
        
        train_ids = []
        valid_ids = []
        test_ids = []
        
        for uid in processed_sequences.keys():
            uid_str = str(uid)
            if uid_str in train_set:
                train_ids.append(uid)
            elif uid_str in valid_set:
                valid_ids.append(uid)
            elif uid_str in test_set:
                test_ids.append(uid)
            # Users not in splits.json are skipped (may have been filtered)
        
        print(f"Applied unified split: Train={len(train_ids)}, Valid={len(valid_ids)}, Test={len(test_ids)}")
    else:
        print(f"WARNING: Unified splits not found at {splits_path}")
        print("Using random split with seed (run generate_splits.py first for consistency)...")
        user_ids = list(processed_sequences.keys())
        np.random.shuffle(user_ids)
        
        n_users = len(user_ids)
        # Use 70/10/20 ratio to match generate_splits.py defaults
        n_train = int(n_users * 0.7)
        n_valid = int(n_users * 0.1)
        
        train_ids = user_ids[:n_train]
        valid_ids = user_ids[n_train : n_train + n_valid]
        test_ids = user_ids[n_train + n_valid :]
        
        print(f"Random split: train={len(train_ids)}, valid={len(valid_ids)}, test={len(test_ids)}")

    train_seqs = [(processed_sequences[u], u) for u in train_ids]
    valid_seqs = [(processed_sequences[u], u) for u in valid_ids]
    test_seqs = [(processed_sequences[u], u) for u in test_ids]

    print(f"Final split: train={len(train_seqs)}, valid={len(valid_seqs)}, test={len(test_seqs)}")

    # Save outputs
    os.makedirs(args.output_dir, exist_ok=True)

    with open(os.path.join(args.output_dir, "lbkt_train.pkl"), "wb") as f:
        pickle.dump(train_seqs, f)
    with open(os.path.join(args.output_dir, "lbkt_valid.pkl"), "wb") as f:
        pickle.dump(valid_seqs, f)
    with open(os.path.join(args.output_dir, "lbkt_test.pkl"), "wb") as f:
        pickle.dump(test_seqs, f)

    # Metadata
    metadata = {
        "num_questions": num_questions,
        "total_q_slots": total_q_slots,
        "n_train": len(train_seqs),
        "n_valid": len(valid_seqs),
        "n_test": len(test_seqs),
        "min_seq_len": args.min_seq_len,
        "qid_to_idx": qid_to_idx,
        "completion_rates": completion_rates,
    }

    with open(os.path.join(args.output_dir, "metadata.json"), "w") as f:
        json.dump(
            {k: v for k, v in metadata.items() if k not in ["qid_to_idx", "completion_rates"]},
            f,
            indent=2,
        )

    with open(os.path.join(args.output_dir, "qid_to_idx.pkl"), "wb") as f:
        pickle.dump(qid_to_idx, f)

    with open(os.path.join(args.output_dir, "completion_rates.pkl"), "wb") as f:
        pickle.dump(completion_rates, f)

    print(f"\nSaved to {args.output_dir}/")
    print(f"  - lbkt_train.pkl ({len(train_seqs)} users)")
    print(f"  - lbkt_valid.pkl ({len(valid_seqs)} users)")
    print(f"  - lbkt_test.pkl ({len(test_seqs)} users)")
    print(f"  - metadata.json")
    print(f"  - qid_to_idx.pkl")
    print(f"  - completion_rates.pkl")

    # Statistics
    all_lens = [len(seq[0][0]) for seq in train_seqs + valid_seqs + test_seqs]
    print(f"\nSequence statistics:")
    print(f"  Min length: {min(all_lens)}")
    print(f"  Max length: {max(all_lens)}")
    print(f"  Mean length: {np.mean(all_lens):.1f}")
    print(f"  Median length: {np.median(all_lens):.1f}")


if __name__ == "__main__":
    main()
